#version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Passw0rd123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  personapi:
    build:
      context: ./PersonApi           # 👈 folder where your Dockerfile and .csproj live
      dockerfile: Dockerfile         # optional if named "Dockerfile"
    container_name: personapi
    ports:
      - "5045:5045"
    environment:
      - ASPNETCORE_URLS=http://+:5045
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PersonDB;User Id=sa;Password=Passw0rd123!;Encrypt=True;TrustServerCertificate=True;
    depends_on:
      - sqlserver

  testperson:
    build:
      context: .                # 👈 root directory (includes TestPerson & PersonApi)
      dockerfile: Dockerfile.test
    container_name: testperson
    depends_on:
      - personapi
    restart: "no"
    entrypoint: ["dotnet", "test", "TestPerson/TestPerson.csproj", "--logger:trx"]

  front-end:
    image: frontend-person:latest
    build:
      context: ./frontendPerson
      dockerfile: Dockerfile
    container_name: front-end
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - personapi

volumes:
  sqlserverdata:
