version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Passw0rd123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  front-end:
    image: frontend-person:latest
    build:
      context: ./frontendPerson         # 👈 your React app folder
      dockerfile: Dockerfile      # optional if the file is named Dockerfile
    container_name: front-end
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - sqlserver

volumes:
  sqlserverdata:
